KEYS: {
    1: parseKey("1B 2D 3C 4A 5A 6C 7B 8C 9B 10A 11B 12B 13C 14C 15A 16B 17B 18A 19B 20C 21A 22C 23A 24A 25A 26B 27B 28A 29C 30C 31C 32B 33D 34B 35C 36A 37D 38A 39D 40A 41C 42D 43B 44C 45C 46A 47A 48D 49C 50C 51B 52A 53C 54A 55B 56B 57A 58C 59A 60C 61B 62C 63C 64D 65D 66A 67C 68B 69A 70C 71B 72C 73A 74B 75D 76A 77B 78D 79A 80D 81A 82B 83D 84A 85D 86A 87B 88C 89D 90B 91C 92B 93A 94D 95A 96C 97D 98D 99C 100A 101B 102A 103A 104B 105B 106C 107C 108D 109A 110A 111C 112C 113A 114C 115C 116D 117A 118D 119C 120B 121D 122C 123B 124C 125A 126D 127D 128D 129D 130B 131D 132C 133A 134B 135D 136C 137B 138A 139A 140C 141B 142D 143C 144C 145B 146A 147C 148D 149B 150C 151D 152C 153B 154C 155D 156C 157B 158D 159B 160C 161C 162D 163B 164B 165B 166A 167B 168C 169B 170B 171A 172D 173A 174B 175C 176A 177D 178C 179D 180C 181D 182D 183A 184C 185B 186B 187A 188B 189A 190D 191D 192B 193B 194A 195A 196B 197A 198D 199C 200A"),
  },
EXPLANATIONS: {
    1: {
      // PART 5: CÂU 101 - 130
      101: "💡 <b>after which</b>: Mệnh đề quan hệ chỉ thời gian, 'sau sự kiện đó người tham gia có thể đặt câu hỏi'.",
      102: "💡 <b>The last antique shop</b>: Cụm danh từ xác định, cửa hàng đồ cổ 'cuối cùng' còn tồn tại.",
      103: "💡 <b>status update</b>: Cụm danh từ ghép chỉ 'bản cập nhật tiến độ/trạng thái dự án'.",
      104: "💡 Cần tính từ sở hữu <b>her</b> đứng trước cụm danh từ 'newly published novel'.",
      105: "💡 <b>the spread of</b>: Danh từ mang nghĩa 'sự lây lan' (của phần mềm độc hại).",
      106: "💡 Trạng từ <b>carefully</b> bổ nghĩa cho động từ quá khứ 'considered'.",
      107: "💡 Cấu trúc câu bị động ở quá khứ: <b>was chosen</b> by the board of directors.",
      108: "💡 Giới từ thời gian: <b>within</b> 24 hours (trong vòng 24 giờ kể từ khi đặt hàng).",
      109: "💡 Động từ nguyên mẫu sau to: <b>to inspect</b> the manufacturing equipment.",
      110: "💡 Cụm cố định: <b>in accordance with</b> (phù hợp với các quy định an toàn).",
      111: "💡 Tính từ bổ nghĩa cho danh từ feedback: <b>constructive</b> feedback (phản hồi mang tính xây dựng).",
      112: "💡 Đại từ phản thân: <b>themselves</b>, vì chủ ngữ là danh từ số nhiều 'The volunteers'.",
      113: "💡 Động từ chia theo chủ ngữ số ít: <b>remains</b> committed to sustainable energy.",
      114: "💡 Cấu trúc nhờ vả/cho phép: <b>enable</b> employees to work remotely.",
      115: "💡 Trạng từ chỉ tần suất/thời gian: <b>regularly</b> inspects the facilities.",
      116: "💡 Từ vựng danh từ: <b>warranty</b> (phiếu bảo hành sản phẩm có hiệu lực trong 2 năm).",
      117: "💡 Phân từ hai làm tính từ rút gọn: <b>detailed</b> instructions (hướng dẫn chi tiết).",
      118: "💡 Liên từ tương phản chỉ nguyên nhân nhượng bộ: <b>Although</b> the flight was delayed,...",
      119: "💡 Cần danh từ sau giới từ for: <b>approval</b> from the city council.",
      120: "💡 Trạng từ bổ nghĩa cho động từ tăng trưởng: sales increased <b>significantly</b>.",
      121: "💡 Giới từ đối lập đi với cụm danh từ: <b>Despite</b> heavy traffic,...",
      122: "💡 Từ vựng tính từ: <b>affordable</b> rates (mức giá phải chăng/hợp lý).",
      123: "💡 Cấu trúc bị động ở hiện tại hoàn thành: <b>have been processed</b>.",
      124: "💡 Trạng từ liên kết: <b>Therefore</b>, all attendees must bring their badges.",
      125: "💡 Danh từ chỉ người: <b>representative</b> from customer support.",
      126: "💡 Từ vựng động từ: <b>exceeded</b> sales expectations (vượt mức kỳ vọng doanh số).",
      127: "💡 Thì quá khứ đơn theo mốc thời gian: <b>launched</b> the campaign last month.",
      128: "💡 Cụm tính từ đi với giới từ: <b>eligible for</b> promotion (đủ điều kiện thăng chức).",
      129: "💡 Liên từ chỉ điều kiện: <b>Provided that</b> all documents are submitted on time,...",
      130: "💡 Từ vựng danh từ: <b>substitute</b> for butter (chất/nguyên liệu thay thế).",

      // PART 6: CÂU 131 - 146
      131: "💡 Thì tương lai đơn: Sự kiện <b>will celebrate</b> kỷ niệm 10 năm thành lập vào tuần tới.",
      132: "💡 Danh từ theo ngữ cảnh doanh nghiệp: mở rộng thêm <b>facilities</b> (cơ sở vật chất/nhà xưởng).",
      133: "💡 Trạng từ liên kết đoạn: <b>Additionally</b>, chúng tôi sẽ tuyển dụng thêm kỹ sư kỹ thuật.",
      134: "💡 Câu điền đoạn phù hợp ngữ cảnh: Lời mời tham gia buổi tiệc tri ân khách hàng thân thiết.",
      135: "💡 Dạng bị động của email nội bộ: Báo cáo tài chính <b>must be submitted</b> trước ngày thứ Sáu.",
      136: "💡 Tính từ chỉ sự chính xác: đảm bảo số liệu <b>accurate</b> trước khi gửi phòng kiểm toán.",
      137: "💡 Đại từ chỉ định thay thế số nhiều: <b>Those</b> who have questions may reach out to HR.",
      138: "💡 Câu điền đoạn: Nhắc nhở nhân viên lưu lại bản sao của hồ sơ công tác phí.",
      139: "💡 Giới từ chỉ khoảng thời gian: thực hiện việc bảo trì hệ thống máy tính <b>during</b> the weekend.",
      140: "💡 Động từ chỉ sự gián đoạn: Dịch vụ ngân hàng số sẽ tạm thời <b>suspend</b> trong 4 tiếng.",
      141: "💡 Trạng từ chỉ kết quả: <b>Consequently</b>, khách hàng nên hoàn tất giao dịch trước 10h tối.",
      142: "💡 Câu điền đoạn: Lời xin lỗi của ban quản trị về sự bất tiện tạm thời này.",
      143: "💡 Tính từ mang tính chất bắt buộc: Tham gia khóa huấn luyện PCCC là <b>mandatory</b>.",
      144: "💡 Động từ nguyên mẫu: nhằm mục đích <b>familiarize</b> nhân viên mới với lối thoát hiểm.",
      145: "💡 Cụm từ cố định: vui lòng kiểm tra lịch làm việc <b>in advance</b> (trước).",
      146: "💡 Câu điền đoạn: Ban tổ chức sẽ cung cấp tài liệu và chứng chỉ sau khi hoàn thành buổi học.",

      // PART 7: CÂU 147 - 200 (ĐỌC HIỂU ĐOẠN ĐƠN & ĐOẠN KÉP)
      147: "💡 <i>Đoạn 1:</i> Thông báo gửi cư dân tòa nhà về việc <b>rải lại nhựa đường khu vực bãi đậu xe</b>.",
      148: "💡 <i>Dòng 4:</i> Cư dân được yêu cầu chuyển xe sang bãi đỗ xe phụ trước <b>7 giờ sáng thứ Năm</b>.",
      149: "💡 <i>Đoạn chat:</i> Mục đích của tin nhắn là <b>yêu cầu đổi phòng họp</b> do phòng hiện tại bị hỏng máy chiếu.",
      150: "💡 <i>Lúc 10:15:</i> Người gửi thông báo đã liên hệ với ban lễ tân để mượn chìa khóa phòng số 3.",
      151: "💡 <i>Email xác nhận:</i> Đơn hàng sách kỹ thuật đã được thanh toán và sẵn sàng giao hàng.",
      152: "💡 <i>Chi tiết đơn hàng:</i> Khách hàng được <b>miễn phí cước vận chuyển</b> vì hóa đơn trên $50.",
      153: "💡 <i>Thông báo tuyển dụng:</i> Vị trí Graphic Designer yêu cầu tối thiểu <b>3 năm kinh nghiệm</b> sử dụng phần mềm Adobe.",
      154: "💡 <i>Quyền lợi công việc:</i> Ứng viên trúng tuyển sẽ được làm việc linh hoạt từ xa 2 ngày mỗi tuần.",
      155: "💡 <i>Bài báo:</i> Chuỗi siêu thị Greenway vừa khai trương thêm chi nhánh mới tại khu vực trung tâm.",
      156: "💡 <i>Đoạn 2:</i> Điểm đặc biệt của chi nhánh mới là tập trung vào <b>các sản phẩm nông sản hữu cơ địa phương</b>.",
      157: "💡 <i>Phỏng vấn:</i> Giám đốc điều hành kỳ vọng siêu thị mới sẽ tạo ra hơn 100 việc làm cho người dân.",
      158: "💡 <i>Vé máy bay:</i> Hành khách hạng thương gia được phép mang theo <b>2 kiện hành lý ký gửi</b>.",
      159: "💡 <i>Quy định giờ:</i> Cổng lên máy bay sẽ đóng <b>15 phút trước giờ cất cánh</b> dự kiến.",
      160: "💡 <i>Đoạn chat nhóm:</i> Bộ phận marketing thảo luận về mẫu thiết kế bao bì cho sản phẩm nước ép mới.",
      161: "💡 <i>Lúc 14:30:</i> Câu 'I'm on it' có nghĩa là nhân viên đồ họa sẽ chỉnh sửa lại logo ngay lập tức.",
      162: "💡 <i>Lịch trình sự kiện:</i> Phiên hội thảo về trí tuệ nhân tạo sẽ diễn ra tại Hội trường A vào buổi chiều.",
      163: "💡 <i>Diễn giả khách mời:</i> Tiến sĩ Aris Thorne sẽ chủ trì buổi thuyết trình chính.",
      164: "💡 <i>Đăng ký sớm:</i> Người tham gia đăng ký trước ngày 15 được giảm 20% giá vé vào cổng.",
      165: "💡 <i>Hướng dẫn bảo quản:</i> Máy giặt công nghiệp phải được vệ sinh lồng giặt định kỳ mỗi tháng một lần.",
      166: "💡 <i>Cảnh báo kỹ thuật:</i> Không sử dụng chất tẩy rửa có nồng độ axit cao vì dễ làm ăn mòn gioăng cao su.",
      167: "💡 <i>Chính sách đổi trả:</i> Hàng hóa chỉ được hoàn tiền trong vòng <b>30 ngày kèm hóa đơn gốc</b>.",
      168: "💡 <i>Ngoại lệ:</i> Các mặt hàng điện tử đã bóc seal sẽ chỉ được đổi sang sản phẩm tương đương.",
      169: "💡 <i>Bài đánh giá:</i> Khách hàng khen ngợi thái độ phục vụ của nhân viên khách sạn nhưng phàn nàn về tốc độ Wi-Fi.",
      170: "💡 <i>Phản hồi quản lý:</i> Khách sạn đang triển khai lắp đặt hệ thống phát sóng cáp quang mới trên toàn bộ các tầng.",
      171: "💡 <i>Biên bản cuộc họp:</i> Ngân sách quý 4 sẽ ưu tiên đầu tư vào việc nâng cấp hệ thống máy chủ nội bộ.",
      172: "💡 <i>Phân công công việc:</i> Ông Miller chịu trách nhiệm tìm kiếm và so sánh báo giá từ các nhà cung cấp phần cứng.",
      173: "💡 <i>Khảo sát ý kiến:</i> Đa số nhân viên mong muốn công ty bổ sung thêm máy pha cà phê tự động ở khu vực pantry.",
      174: "💡 <i>Đoạn kép (Email & Đơn vị):</i> Khách hàng khiếu nại về việc giao trễ bộ bàn làm việc bằng gỗ sồi.",
      175: "💡 <i>Đối chiếu hóa đơn:</i> Mã đơn hàng bị giao nhầm sang địa chỉ chi nhánh phía Bắc thay vì nhà riêng.",
      176: "💡 <i>Đoạn kép:</i> Công ty nội thất đề nghị <b>hoàn lại toàn bộ phí vận chuyển</b> và tặng kèm phiếu giảm giá 15%.",
      177: "💡 <i>Đoạn kép:</i> Lịch trình chuyến bay công tác của ông Tanaka tại hội nghị khách hàng ở Chicago.",
      178: "💡 <i>Đối chiếu giờ:</i> Do chuyến bay nối chuyến bị hoãn, ông sẽ đến muộn hơn so với tiệc tối khai mạc.",
      179: "💡 <i>Xử lý tình huống:</i> Đồng nghiệp đề xuất dời lịch thuyết trình của ông Tanaka sang sáng ngày thứ Hai.",
      180: "💡 <i>Đoạn kép:</i> Đề án chuyển đổi xanh của trường Đại học: Lắp đặt hệ thống năng lượng địa nhiệt và điện mặt trời.",
      181: "💡 <i>Mục tiêu:</i> Cắt giảm 40% lượng khí thải carbon của toàn bộ khuôn viên trường học vào năm 2030.",
      182: "💡 <i>Kinh phí:</i> Một nửa nguồn vốn thực hiện dự án được tài trợ bởi quỹ phát triển môi trường của thành phố.",
      183: "💡 <i>Đoạn ba:</i> Quảng cáo khóa đào tạo quản lý dự án dành cho các kỹ sư công nghệ thông tin.",
      184: "💡 <i>Hồ sơ học viên:</i> Học viên cần nộp bản sao bằng cử nhân và thư giới thiệu từ quản lý trực tiếp.",
      185: "💡 <i>Lịch học:</i> Khóa học được tổ chức vào các buổi tối thứ Ba và thứ Năm thông qua nền tảng trực tuyến.",
      186: "💡 <i>Đoạn ba:</i> Chuỗi khách sạn Bella Vista mở gói dịch vụ trọn gói cho tiệc cưới ngoài trời bên bãi biển.",
      187: "💡 <i>Đối chiếu email:</i> Khách hàng chọn gói thực đơn Hải sản cao cấp và yêu cầu chuẩn bị thêm bánh kem ăn kiêng.",
      188: "💡 <i>Hợp đồng:</i> Khách hàng cần đặt cọc trước 30% giá trị hợp đồng để giữ sảnh tiệc vào ngày cuối tuần.",
      189: "💡 <i>Đoạn ba:</i> Cuộc thi sáng tạo ý tưởng kinh doanh dành cho sinh viên các trường đại học khối kinh tế.",
      190: "💡 <i>Cơ cấu giải thưởng:</i> Đội giành giải Nhất sẽ nhận được $10,000 tiền mặt và 6 tháng ươm tạo doanh nghiệp miễn phí.",
      191: "💡 <i>Tiêu chí chấm điểm:</i> Tính khả thi của mô hình kinh doanh chiếm 40% tổng số điểm đánh giá.",
      192: "💡 <i>Đoạn ba:</i> Email trao đổi giữa bộ phận thu mua và xưởng may mặc về lô hàng áo khoác đồng phục mùa đông.",
      193: "💡 <i>Vấn đề phát sinh:</i> Màu sắc của vải thực tế bị nhạt hơn so với mẫu duyệt ban đầu do lỗi nhuộm màu.",
      194: "💡 <i>Giải pháp:</i> Xưởng may cam kết sản xuất lại lô hàng mới và giao đúng hạn trước đợt rét đầu mùa.",
      195: "💡 <i>Đoạn ba:</i> Kế hoạch tái cấu trúc không gian làm việc của công ty công nghệ sang mô hình bàn làm việc linh hoạt (hot-desking).",
      196: "💡 <i>Mục đích:</i> Tối ưu hóa diện tích văn phòng khi nhân viên có lịch làm việc hybrid kết hợp tại nhà.",
      197: "💡 <i>Quy định mới:</i> Mọi người cần đặt trước chỗ ngồi qua ứng dụng nội bộ ít nhất 24 giờ trước khi đến công ty.",
      198: "💡 <i>Phản hồi:</i> Khu vực làm việc yên tĩnh được bố trí ở tầng 5 dành cho những ai cần sự tập trung cao độ.",
      199: "💡 <i>Đoạn cuối:</i> Bản tin nội bộ chúc mừng phòng R&D vừa được cấp bằng sáng chế công nghệ pin thể rắn mới.",
      200: "💡 <i>Tầm nhìn:</i> Công nghệ pin mới sẽ giúp tăng tuổi thọ thiết bị lên 50% và giảm một nửa thời gian sạc điện."
    }
  }
